const { PERMISSIONS } = require('./permissions');

const ROLES = Object.freeze({
  SUPER_ADMIN: Object.freeze([
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_MANAGE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_MANAGE,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ORGANIZATIONS_READ,
    PERMISSIONS.ORGANIZATIONS_CREATE,
    PERMISSIONS.ORGANIZATIONS_UPDATE,
    PERMISSIONS.ORGANIZATIONS_SUSPEND,

    PERMISSIONS.DRIVERS_READ,
    PERMISSIONS.DRIVERS_MANAGE,

    PERMISSIONS.PROPRIETAIRES_READ,
    PERMISSIONS.PROPRIETAIRES_MANAGE,
    PERMISSIONS.SOCIETES_READ,
    PERMISSIONS.SOCIETES_MANAGE,

    PERMISSIONS.VEHICLES_READ,
    PERMISSIONS.VEHICLES_MANAGE,

    PERMISSIONS.CONTRACTS_READ,
    PERMISSIONS.CONTRACTS_MANAGE,
    PERMISSIONS.LIVRAISONS_READ,
    PERMISSIONS.LIVRAISONS_MANAGE,

    PERMISSIONS.FLEET_READ,
    PERMISSIONS.FLEET_MANAGE,

    PERMISSIONS.COOP_READ,
    PERMISSIONS.COOP_MANAGE,

    PERMISSIONS.PLANS_READ,
    PERMISSIONS.PLANS_MANAGE,

    PERMISSIONS.SUBSCRIPTIONS_READ,
    PERMISSIONS.SUBSCRIPTIONS_MANAGE,

    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_MANAGE,

    PERMISSIONS.FINANCES_READ,
    PERMISSIONS.FINANCES_MANAGE,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.TARIFS_READ,
    PERMISSIONS.TARIFS_MANAGE,

    PERMISSIONS.RULES_READ,
    PERMISSIONS.RULES_MANAGE,

    PERMISSIONS.MONITORING_READ,

    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_MANAGE,

    PERMISSIONS.ASSISTANCE_REQUEST,
    PERMISSIONS.ASSISTANCE_APPROVE,
    PERMISSIONS.ASSISTANCE_REVOKE,

    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.LOGS_READ,
    PERMISSIONS.LANDING_MANAGE,
  ]),

  ADMIN: Object.freeze([
    PERMISSIONS.NOTIFICATIONS_READ,

    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_MANAGE,
    PERMISSIONS.MAINTENANCE_READ,

    PERMISSIONS.USERS_READ,

    PERMISSIONS.ORGANIZATIONS_READ,

    PERMISSIONS.DRIVERS_READ,
    PERMISSIONS.VEHICLES_READ,

    PERMISSIONS.PROPRIETAIRES_READ,
    PERMISSIONS.SOCIETES_READ,

    PERMISSIONS.CONTRACTS_READ,
    PERMISSIONS.LIVRAISONS_READ,
    PERMISSIONS.LIVRAISONS_MANAGE,

    PERMISSIONS.FLEET_READ,
    PERMISSIONS.FLEET_MANAGE,

    PERMISSIONS.COOP_READ,
    PERMISSIONS.COOP_MANAGE,

    PERMISSIONS.PLANS_READ,
    PERMISSIONS.SUBSCRIPTIONS_READ,

    PERMISSIONS.BILLING_READ,

    PERMISSIONS.FINANCES_READ,
    PERMISSIONS.FINANCES_MANAGE,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.TARIFS_READ,
    PERMISSIONS.TARIFS_MANAGE,

    PERMISSIONS.RULES_READ,

    PERMISSIONS.MONITORING_READ,

    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_MANAGE,

    PERMISSIONS.ASSISTANCE_REQUEST,

    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.LOGS_READ,
    PERMISSIONS.LANDING_MANAGE,
  ]),

  FLEET_MANAGER: Object.freeze([
    PERMISSIONS.MESSAGES_READ,

    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_MANAGE,

    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_MANAGE,

    PERMISSIONS.DRIVERS_READ,
    PERMISSIONS.DRIVERS_MANAGE,

    PERMISSIONS.PROPRIETAIRES_READ,
    PERMISSIONS.PROPRIETAIRES_MANAGE,
    PERMISSIONS.SOCIETES_READ,
    PERMISSIONS.SOCIETES_MANAGE,
    PERMISSIONS.VEHICLES_READ,

    PERMISSIONS.CONTRACTS_READ,
    PERMISSIONS.CONTRACTS_MANAGE,
    PERMISSIONS.LIVRAISONS_READ,
    PERMISSIONS.LIVRAISONS_MANAGE,
    PERMISSIONS.VEHICLES_MANAGE,

    PERMISSIONS.FLEET_READ,
    PERMISSIONS.FLEET_MANAGE,

    PERMISSIONS.SUBSCRIPTIONS_READ,

    PERMISSIONS.BILLING_READ,

    PERMISSIONS.FINANCES_READ,
    PERMISSIONS.FINANCES_MANAGE,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.TARIFS_READ,
    PERMISSIONS.TARIFS_MANAGE,

    PERMISSIONS.RULES_READ,

    PERMISSIONS.MONITORING_READ,

    PERMISSIONS.SUPPORT_READ,

    PERMISSIONS.ASSISTANCE_REQUEST,
  ]),

  COOPERATIVE: Object.freeze([
    PERMISSIONS.MESSAGES_READ,

    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_MANAGE,

    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_MANAGE,

    PERMISSIONS.DRIVERS_READ,
    PERMISSIONS.DRIVERS_MANAGE,

    PERMISSIONS.PROPRIETAIRES_READ,
    PERMISSIONS.PROPRIETAIRES_MANAGE,
    PERMISSIONS.SOCIETES_READ,
    PERMISSIONS.SOCIETES_MANAGE,
    PERMISSIONS.VEHICLES_READ,

    PERMISSIONS.CONTRACTS_READ,
    PERMISSIONS.CONTRACTS_MANAGE,
    PERMISSIONS.LIVRAISONS_READ,
    PERMISSIONS.LIVRAISONS_MANAGE,
    PERMISSIONS.VEHICLES_MANAGE,

    PERMISSIONS.COOP_READ,
    PERMISSIONS.COOP_MANAGE,

    PERMISSIONS.SUBSCRIPTIONS_READ,

    PERMISSIONS.BILLING_READ,

    PERMISSIONS.FINANCES_READ,
    PERMISSIONS.FINANCES_MANAGE,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.TARIFS_READ,
    PERMISSIONS.TARIFS_MANAGE,

    PERMISSIONS.RULES_READ,

    PERMISSIONS.MONITORING_READ,

    PERMISSIONS.SUPPORT_READ,

    PERMISSIONS.ASSISTANCE_REQUEST,
  ]),

  DRIVER: Object.freeze([
    PERMISSIONS.FINANCES_READ,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_MANAGE,
    PERMISSIONS.TARIFS_READ,
    PERMISSIONS.VEHICLES_READ,
  ]),
});

function getRolePermissions(role) {
  return ROLES[role] || [];
}

function hasPermission(role, permission) {
  return getRolePermissions(role).includes(permission);
}

module.exports = {
  ROLES,
  getRolePermissions,
  hasPermission,
};
